name: bazaar_app
description: "A Bazaar App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  provider: ^6.1.1
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  shared_preferences: ^2.5.3

  http: ^1.4.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  stream_transform: ^2.0.0
  flutter_dotenv: ^5.1.0

  lottie: ^3.3.1
  flutter_svg: ^2.0.10
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Biro Script
      fonts:
        - asset: assets/fonts/Biro_Script_reduced.ttf

  assets:
    - .env
    - assets/images/
    - assets/animations/splash_screen_1.json
    - assets/animations/splash_screen_2.json
